version: '3.8'

services:
  backend:
    image: tylernow/family-wishlist:dev-backend
    environment:
      - ENVIRONMENT=dev
      - DEV_DATABASE_URL=sqlite:///./data/dev-wishlist.db
      - PROD_DATABASE_URL=sqlite:///./data/wishlist.db
      - PUID=${PUID:-1000} # User ID for file permissions, defaults to 1000 if not set
      - PGID=${PGID:-1000} # Group ID for file permissions, defaults to 1000 if not set
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    image: tylernow/family-wishlist:dev-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend
