version: '3.8'

services:
  backend:
    image: tylernow/family-wishlist:latest-backend
    environment:
      - ENVIRONMENT=prod
      - DEV_DATABASE_URL=sqlite:///./data/dev-wishlist.db
      - PROD_DATABASE_URL=sqlite:///./data/wishlist.db
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    image: tylernow/family-wishlist:latest-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend
